// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOdAEtjrWg4l0Ln0EkbMQMFTsnSc0wWws',
    appId: '1:607600253943:web:e503f636f6680747ac6cf2',
    messagingSenderId: '607600253943',
    projectId: 'subscription-manager-gori',
    authDomain: 'subscription-manager-gori.firebaseapp.com',
    storageBucket: 'subscription-manager-gori.firebasestorage.app',
    measurementId: 'G-6EKY67DYGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQ455lyoO9QSfA443IvbWbJ1FI4JEPVI',
    appId: '1:607600253943:android:40347355e2d44151ac6cf2',
    messagingSenderId: '607600253943',
    projectId: 'subscription-manager-gori',
    storageBucket: 'subscription-manager-gori.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GOIXrb2JGBx7v_QicX_8N49spbEPNb4',
    appId: '1:607600253943:ios:472cc85d6471aca9ac6cf2',
    messagingSenderId: '607600253943',
    projectId: 'subscription-manager-gori',
    storageBucket: 'subscription-manager-gori.firebasestorage.app',
    iosBundleId: 'co.jp.optim.subscriptionManager',
  );
}
